# Generated by Django 2.2.12 on 2020-06-15 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True)),
                ('location', models.CharField(default='', max_length=200)),
                ('qualifications', models.CharField(default='See certifications', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('start_date', models.DateField(default=None)),
                ('end_date', models.DateField(blank=True, default=None)),
                ('location', models.CharField(default='', max_length=200)),
                ('role', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Lauren Alie', max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('linkedIn', models.URLField(blank=True)),
                ('headline', models.TextField(blank=True, help_text='Write a few sentences to describe where you are in your career and what you stand for.')),
                ('technical_skills', models.TextField(help_text="Programming languages and technical tools you're competent with.")),
                ('references', models.TextField(blank=True)),
                ('last_updated_date', models.DateTimeField()),
                ('extracurriculars', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_extracurriculars', to='blog.Experience')),
                ('notable_achievements', models.ForeignKey(blank=True, help_text='This can include hackathon participation, online courses and certifications.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_achievements', to='blog.Experience')),
                ('other_work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_other_experience', to='blog.Experience')),
                ('technology_experience', models.ForeignKey(help_text='Any work experience in the tech industry.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_technology_experience', to='blog.Experience')),
                ('volunteering_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_volunteering_experience', to='blog.Experience')),
            ],
        ),
    ]
