# Generated by Django 2.2.12 on 2020-06-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200601_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_featured',
            new_name='featured',
        ),
    ]
