# Generated by Django 2.2.12 on 2020-06-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200615_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='extracurriculars',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='notable_achievements',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='other_work_experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='technology_experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='volunteering_experience',
        ),
    ]
