# Generated by Django 2.2.12 on 2020-06-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200615_1149'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.AddField(
            model_name='resume',
            name='education_experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_education', to='blog.Experience'),
        ),
        migrations.AddField(
            model_name='resume',
            name='extracurriculars',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_extracurriculars', to='blog.Experience'),
        ),
        migrations.AddField(
            model_name='resume',
            name='notable_achievements',
            field=models.ForeignKey(blank=True, default=1, help_text='This can include hackathon participation, online courses and certifications.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_achievements', to='blog.Experience'),
        ),
        migrations.AddField(
            model_name='resume',
            name='other_work_experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_other_experience', to='blog.Experience'),
        ),
        migrations.AddField(
            model_name='resume',
            name='technology_experience',
            field=models.ForeignKey(default=1, help_text='Any work experience in the tech industry.', on_delete=django.db.models.deletion.CASCADE, related_name='employee_technology_experience', to='blog.Experience'),
        ),
        migrations.AddField(
            model_name='resume',
            name='volunteering_experience',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employee_volunteering_experience', to='blog.Experience'),
        ),
    ]
