# Generated by Django 2.2.12 on 2020-06-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200615_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='extracurriculars',
        ),
        migrations.AddField(
            model_name='resume',
            name='extracurriculars',
            field=models.ManyToManyField(default=1, related_name='employee_extracurriculars', to='blog.Experience'),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='notable_achievements',
        ),
        migrations.AddField(
            model_name='resume',
            name='notable_achievements',
            field=models.ManyToManyField(blank=True, default=1, help_text='This can include hackathon participation, online courses and certifications.', related_name='employee_achievements', to='blog.Experience'),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='other_work_experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='other_work_experience',
            field=models.ManyToManyField(default=1, related_name='employee_other_experience', to='blog.Experience'),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='technology_experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='technology_experience',
            field=models.ManyToManyField(default=1, help_text='Any work experience in the tech industry.', related_name='employee_technology_experience', to='blog.Experience'),
        ),
        migrations.RemoveField(
            model_name='resume',
            name='volunteering_experience',
        ),
        migrations.AddField(
            model_name='resume',
            name='volunteering_experience',
            field=models.ManyToManyField(default=1, related_name='employee_volunteering_experience', to='blog.Experience'),
        ),
    ]
